name: Sound and Sunlight
favicon: null
layout_spectrum: 0.12672
typography_spectrum: 0.82208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272d39'
    - '#a0a4a9'
    - '#6e7b85'
    - '#070419'
  brandStrength: 1
  lightness: 0.46561919222585857
  saturation: 0.11762846331112087
  rhythmicContrast: 0.7219778704456985
purpose: []
